version: '3'
services:
  mongodb:
     image: mongo
     networks:
          - backend
     ports:
         - 27017:27017
  account:
    build: .
    restart: always
    networks:
      - backend
    environment:
      JWT_KEY: "1342787847346423534"
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:management
    networks:
        - backend
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch
    networks:
      - backend
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana
    networks:
      - backend
    ports:
      - 5601:5601
  logstash:
    image: logstash
    volumes:
      - /opt/elk/logstash:/opt/config/
    command: logstash -f /opt/config/logstash.conf
    networks:
      - backend
    ports:
      - 7000:5000
networks:
  backend: