graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

spring:
  data:
    mongodb:
      auto-connect-retry: true
  rabbit:
    connection-factory:
      host: rabbitmq
      port: 5672
      username: guest
      password: guest