graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

#spring.data.mongodb.uri: mongodb://mongo:27017
#spring.data.mongodb.database: account
spring.data.mongodb.auto-connect-retry: true