graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

logging:
  config:
     classpath: "logback.xml"

spring:
  data:
    mongodb:
      auto-connect-retry: true